//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFG_AIK_OscarJoseAbeldaFernandez.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TFG_AIK_OscarJoseAbeldaFernandez.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imposible to find the request experience. .
        /// </summary>
        internal static string ExperienceNotFound {
            get {
                return ResourceManager.GetString("ExperienceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This aplication was designed 1920 x 1080 screen resolution.
        ///Running it in a diferent resolution may result in incorrect layout and reduced functionality.
        ///Do you wish to continue?.
        /// </summary>
        internal static string NotOptimalScreenResolutionMessage {
            get {
                return ResourceManager.GetString("NotOptimalScreenResolutionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Optimal Screen Resolution.
        /// </summary>
        internal static string NotOptimalScreenResolutionTitle {
            get {
                return ResourceManager.GetString("NotOptimalScreenResolutionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to quit?.
        /// </summary>
        internal static string OnClosingMessage {
            get {
                return ResourceManager.GetString("OnClosingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing.
        /// </summary>
        internal static string OnClosingTitle {
            get {
                return ResourceManager.GetString("OnClosingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {2:0}:{1:00}.{0:0}.
        /// </summary>
        internal static string timeFormat {
            get {
                return ResourceManager.GetString("timeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The experience type &apos;{0}&apos; is unknown.
        /// </summary>
        internal static string UnExistingExperienceType {
            get {
                return ResourceManager.GetString("UnExistingExperienceType", resourceCulture);
            }
        }
    }
}
